name: Build and test

on:
  workflow_call:

env:
  MODE: CI

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: c-hive/gha-yarn-cache@v2

      - run: yarn install

      - run: yarn build
    
      - run: yarn test:unit
      - run: yarn test:e2e
          