name: Release

on:
  workflow_dispatch:

jobs:
  build-test:
    uses: ./.github/workflows/build-test.part.yml

  release:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
      - run: yarn install
      - run: yarn release:ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
